site_name: PYTHON_TOOLS
# Add repository metadate for more integration and ease-of-use
repo_name: python-tools
repo_url: https://github.com/grigaut/python-tools

theme:
  name: "material"
  logo: assets/logo/NERSC.png
  favicon: assets/logo/NERSC.png
  features:
    - navigation.tabs               # Tabs
    - navigation.tabs.sticky        # Above tabs stay displayed
    - navigation.indexes            # Attach documents to sections
    - navigation.instant
    - navigation.footer
    - navigation.top                # Scroll back to top button
    - content.code.annotate         # Admonitions
    - content.code.copy             # copy code block

nav:
  - First page:
    - index.md
  - Extensions Examples:
    - extension_examples.md
  - Code Reference: reference/

plugins:
  - literate-nav:
      nav_file: SUMMARY.md          # To auto-generate paths
  - gen-files:
      scripts:
        - docs/scripts/docs_generator.py   # To auto generate 'Code Reference' Section
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy  # To parse docstrings
            docstring_section_style: spacy
            heading_level: 3
            show_root_toc_entry: false
            show_if_no_docstring: true
            showsubmodules: true

markdown_extensions:
  - admonition
  - pymdownx.superfences      # code blocks
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true   # Tabs
  - footnotes
