[tool.poetry]
name = "python-tools"
version = "0.1.0"
description = ""
authors = ["Gaétan Rigaut <gaetanrigaut.s@gmail.com>"]
readme = "README.md"
packages = [{ include = "python_tools" }]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.0"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ruff = "^0.0.260"
pre-commit = "^3.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 79
target-version = "py311"
